# print("process_money.report()")
# process_money.report()

# print("\ndrink_menu.get_items()")
# print(drink_menu.get_items())

# print("\ncoffee_maker.report")
# coffee_maker.report()

# print("\nset variable to drink_menu.find_drink(latte)")
# mlatte = (drink_menu.find_drink('latte'))
# print("\nprint(variable.ingredients)")
# print(mlatte.ingredients)
# print("\nprint(variable.name)")
# print(mlatte.name)
# print("\nprint(variable.cost)")
# print(mlatte.cost)
# print("\ncoffee_maker.make_coffee(variable)")
# coffee_maker.make_coffee(mlatte)
# print("\nnew report")
# coffee_maker.report()
# print("\nmoney is not adjusted")
# process_money.report()
# print("\n***method for MoneyMachine missing from PDF - check process_coins in money_machine.py to figure out how to update money report***")

# print("\nhere is the process_coins object in action")
# total = process_money.process_coins()
# process_money.make_payment(15)
# process_money.report()